import 'reflect-metadata';

import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { config as loadDotenv } from 'dotenv';
import { DataSource } from 'typeorm';

import { ALL_ENTITIES } from '$/core/orm/entities';

/**
 * Generates the **DB Handover Package** (dossier 0.26) — the artifact given to
 * the DB team, who provision the real databases.
 *
 *   npm run handover:generate
 *
 * Everything is derived from the LIVE, migrated database and from
 * `docker/mysql/grants.sql`. Nothing is hand-written, because a hand-maintained
 * schema document drifts from the migrations the moment anyone forgets to
 * update it — and a drifted handover produces a production database that
 * silently differs from the one the service was built against.
 *
 * The DDL comes from `mysqldump --no-data`, i.e. what MySQL itself reports it
 * has, not what TypeORM intended. That difference is load-bearing: it captures
 * the generated `deleted_marker` column (0.29) and the `platform_settings`
 * CHECK constraint, which TypeORM's MySQL driver silently drops from
 * `@Check()` decorators (verified in Phase 2).
 */
loadDotenv();

const OUTPUT_DIR = 'docs/db-handover';

interface DbTarget {
  url: string;
  host: string;
  port: string;
  user: string;
  password: string;
  database: string;
}

function parseUrl(raw: string): DbTarget {
  const parsed = new URL(raw);

  return {
    url: raw,
    host: parsed.hostname,
    port: parsed.port || '3306',
    user: decodeURIComponent(parsed.username),
    password: decodeURIComponent(parsed.password),
    database: parsed.pathname.replace(/^\//, ''),
  };
}

/**
 * Runs mysqldump inside the local container.
 *
 * The password goes through the environment, never argv: an argument is
 * visible in `ps` to every user on the host, and this script exists to produce
 * a security document.
 */
function dumpSchema(target: DbTarget): string {
  return execFileSync(
    'docker',
    [
      'exec',
      '-i',
      '-e',
      'MYSQL_PWD',
      'papi-authority-mysql',
      'mysqldump',
      `--host=127.0.0.1`,
      `--user=${target.user}`,
      '--no-data',
      // The migrator principal has no PROCESS privilege — deliberately, since
      // it needs DDL on one schema and nothing server-wide. Without this flag
      // mysqldump tries to enumerate tablespaces and errors.
      '--no-tablespaces',
      '--skip-comments',
      '--skip-add-drop-table',
      '--skip-set-charset',
      '--single-transaction',
      target.database,
    ],
    { env: { ...process.env, MYSQL_PWD: target.password }, encoding: 'utf8', maxBuffer: 32e6 },
  );
}

async function collectFacts(target: DbTarget): Promise<{
  tables: number;
  foreignKeys: number;
  indexes: number;
  migrations: string[];
  catalogRows: number;
}> {
  const dataSource = new DataSource({
    type: 'mysql',
    url: target.url,
    entities: ALL_ENTITIES,
    synchronize: false,
  });
  await dataSource.initialize();

  try {
    const one = async (sql: string): Promise<number> => {
      const rows = await dataSource.query<{ n: string | number }[]>(sql);
      return Number(rows[0]?.n ?? 0);
    };

    const tables = await one(
      `SELECT COUNT(*) n FROM information_schema.tables WHERE table_schema = DATABASE() AND table_type = 'BASE TABLE'`,
    );
    const foreignKeys = await one(
      `SELECT COUNT(*) n FROM information_schema.referential_constraints WHERE constraint_schema = DATABASE()`,
    );
    const indexes = await one(
      `SELECT COUNT(DISTINCT table_name, index_name) n FROM information_schema.statistics WHERE table_schema = DATABASE()`,
    );
    const catalogRows = await one(`SELECT COUNT(*) n FROM permission_catalog`);

    const migrationRows = await dataSource.query<{ name: string }[]>(
      `SELECT name FROM migrations ORDER BY timestamp ASC`,
    );

    return {
      tables,
      foreignKeys,
      indexes,
      catalogRows,
      migrations: migrationRows.map((row) => row.name),
    };
  } finally {
    await dataSource.destroy();
  }
}

async function main(): Promise<void> {
  const migratorUri = process.env.DB_MIGRATOR_URI;
  if (!migratorUri) {
    throw new Error('DB_MIGRATOR_URI must be set to generate the handover package.');
  }

  const target = parseUrl(migratorUri);

  mkdirSync(OUTPUT_DIR, { recursive: true });

  const schema = dumpSchema(target);
  const grants = readFileSync('docker/mysql/grants.sql', 'utf8');

  writeFileSync(
    join(OUTPUT_DIR, '01-schema.sql'),
    `-- GENERATED by \`npm run handover:generate\` — DO NOT EDIT BY HAND.\n` +
      `-- Source: mysqldump --no-data of a fully migrated database.\n` +
      `-- Regenerate after any migration; never patch this file.\n\n` +
      schema,
    'utf8',
  );

  writeFileSync(
    join(OUTPUT_DIR, '02-principals-and-grants.sql'),
    `-- GENERATED by \`npm run handover:generate\` — DO NOT EDIT BY HAND.\n` +
      `-- Verbatim copy of docker/mysql/grants.sql, which is the single source\n` +
      `-- of truth for every grant. Edit that file, then regenerate.\n\n` +
      grants,
    'utf8',
  );

  const facts = await collectFacts(target);

  writeFileSync(join(OUTPUT_DIR, 'facts.json'), `${JSON.stringify(facts, null, 2)}\n`, 'utf8');

  process.stdout.write(
    `handover: wrote ${OUTPUT_DIR}/ — ${facts.tables} tables, ${facts.foreignKeys} FKs, ` +
      `${facts.indexes} indexes, ${facts.migrations.length} migrations, ` +
      `${facts.catalogRows} permissions\n`,
  );
}

main().catch((error: unknown) => {
  process.stderr.write(`handover: ${error instanceof Error ? error.message : String(error)}\n`);
  process.exitCode = 1;
});
