import 'reflect-metadata';

import { config as loadDotenv } from 'dotenv';
import { DataSource } from 'typeorm';

import { PermissionCatalogEntity } from '$/api/authorization/entities/permission-catalog.entity';
import { catalogRefOf, flattenCatalog } from '$/api/authorization/permission-catalog';
import type { CatalogEntry } from '$/api/authorization/permission-catalog';
import { ALL_ENTITIES } from '$/core/orm/entities';

/**
 * Catalog <-> `permission_catalog` drift tooling (dossier 0.38 / 0.40).
 *
 *   permissions:check               fail (exit 1) if the table and the code disagree
 *   permissions:generate-migration  emit a migration for the difference
 *
 * `check` runs in the build/CI. There is deliberately NO boot-time assertion:
 * that could only fail after a bad deploy is already live, and a service that
 * refuses to start is worse than a permission that is temporarily not
 * grantable. The `permission_catalog` foreign key already makes the dangerous
 * direction — granting something that does not exist — fail at write time.
 */
loadDotenv();

interface Diff {
  missingInDb: CatalogEntry[];
  extraInDb: { section: string; permissionKey: string; kind: string }[];
}

async function computeDiff(): Promise<Diff> {
  const url = process.env.DB_MIGRATOR_URI;
  if (!url) throw new Error('DB_MIGRATOR_URI must be set to run permission tooling.');

  const dataSource = new DataSource({
    type: 'mysql',
    url,
    entities: ALL_ENTITIES,
    synchronize: false,
  });
  await dataSource.initialize();

  try {
    const stored = await dataSource.getRepository(PermissionCatalogEntity).find();
    const storedKeys = new Set(stored.map((row) => `${row.kind}:${catalogRefOf(row)}`));
    const codeEntries = flattenCatalog();
    const codeKeys = new Set(codeEntries.map((entry) => `${entry.kind}:${catalogRefOf(entry)}`));

    return {
      missingInDb: codeEntries.filter((e) => !storedKeys.has(`${e.kind}:${catalogRefOf(e)}`)),
      extraInDb: stored.filter((r) => !codeKeys.has(`${r.kind}:${catalogRefOf(r)}`)),
    };
  } finally {
    await dataSource.destroy();
  }
}

function reportDiff(diff: Diff): boolean {
  const clean = diff.missingInDb.length === 0 && diff.extraInDb.length === 0;

  if (clean) {
    console.log(
      `permissions: catalog and database agree (${flattenCatalog().length} permissions).`,
    );
    return true;
  }

  console.error('permissions: DRIFT between the code catalog and permission_catalog\n');
  for (const entry of diff.missingInDb) {
    console.error(`  in code, MISSING from db : ${entry.kind} ${catalogRefOf(entry)}`);
  }
  for (const row of diff.extraInDb) {
    console.error(`  in db, MISSING from code : ${row.kind} ${catalogRefOf(row)}`);
  }
  console.error('\nRun `npm run permissions:generate-migration`, then `npm run migration:run`.');
  return false;
}

function emitMigration(diff: Diff): void {
  if (diff.missingInDb.length === 0 && diff.extraInDb.length === 0) {
    console.log('permissions: nothing to generate — catalog and database agree.');
    return;
  }

  const inserts = diff.missingInDb
    .map(
      (e) => `            ("${e.section}", "${e.permissionKey}", "${e.kind}", "${e.description}")`,
    )
    .join(',\n');

  // Deletions are emitted commented out on purpose: a catalog entry can only be
  // removed once nothing references it, and the FK is RESTRICT, so an
  // unconsidered DELETE here would fail the migration mid-run. Removing a
  // permission is a deliberate act that must first revoke every grant using it.
  const deletes = diff.extraInDb
    .map(
      (r) =>
        `        // await queryRunner.query(\`DELETE FROM \\\`permission_catalog\\\` WHERE section='${r.section}' AND permission_key='${r.permissionKey}' AND kind='${r.kind}'\`);`,
    )
    .join('\n');

  console.log(
    [
      '// Generated by `npm run permissions:generate-migration`.',
      '// Save as src/migrations/<timestamp>-SyncPermissionCatalog.ts',
      '',
      "import { MigrationInterface, QueryRunner } from 'typeorm';",
      '',
      'export class SyncPermissionCatalog implements MigrationInterface {',
      '    public async up(queryRunner: QueryRunner): Promise<void> {',
      inserts
        ? `        await queryRunner.query(\`INSERT INTO \\\`permission_catalog\\\` (section, permission_key, kind, description) VALUES\n${inserts}\`);`
        : '        // no additions',
      deletes ? `\n        // Review before enabling — the FK is RESTRICT:\n${deletes}` : '',
      '    }',
      '',
      '    public async down(): Promise<void> {',
      '        // Intentionally empty: removing catalog rows requires revoking',
      '        // every grant that references them first.',
      '    }',
      '}',
    ].join('\n'),
  );
}

const mode = process.argv[2];

void computeDiff()
  .then((diff) => {
    if (mode === 'generate') {
      emitMigration(diff);
      return;
    }
    if (!reportDiff(diff)) process.exit(1);
  })
  .catch((error: unknown) => {
    console.error('permissions: failed —', error);
    process.exit(1);
  });
