// Generated by `npm run permissions:generate-migration`.
// Catalog rows are owned by code (dossier 0.38); this migration materialises them.

import { MigrationInterface, QueryRunner } from 'typeorm';

export class SyncPermissionCatalog1786014020134 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`INSERT INTO \`permission_catalog\` (section, permission_key, kind, description) VALUES
            ("users", "users", "page", "users page"),
            ("users", "view", "api", "users.view endpoint"),
            ("users", "create", "api", "users.create endpoint"),
            ("users", "update", "api", "users.update endpoint"),
            ("users", "delete", "api", "users.delete endpoint"),
            ("users", "invite", "api", "users.invite endpoint"),
            ("users", "approve", "api", "users.approve endpoint"),
            ("users", "unauthorize", "api", "users.unauthorize endpoint"),
            ("userRoles", "userRoles", "page", "userRoles page"),
            ("userRoles", "view", "api", "userRoles.view endpoint"),
            ("userRoles", "create", "api", "userRoles.create endpoint"),
            ("userRoles", "update", "api", "userRoles.update endpoint"),
            ("userRoles", "delete", "api", "userRoles.delete endpoint"),
            ("projects", "projects", "page", "projects page"),
            ("projects", "view", "api", "projects.view endpoint"),
            ("projects", "create", "api", "projects.create endpoint"),
            ("projects", "update", "api", "projects.update endpoint"),
            ("projects", "delete", "api", "projects.delete endpoint"),
            ("projectOperators", "projectOperators", "page", "projectOperators page"),
            ("projectOperators", "view", "api", "projectOperators.view endpoint"),
            ("projectOperators", "create", "api", "projectOperators.create endpoint"),
            ("projectOperators", "update", "api", "projectOperators.update endpoint"),
            ("projectOperators", "delete", "api", "projectOperators.delete endpoint"),
            ("projectLimits", "projectLimits", "page", "projectLimits page"),
            ("projectLimits", "view", "api", "projectLimits.view endpoint"),
            ("projectLimits", "update", "api", "projectLimits.update endpoint"),
            ("adminPanels", "adminPanels", "page", "adminPanels page"),
            ("adminPanels", "view", "api", "adminPanels.view endpoint"),
            ("adminPanels", "create", "api", "adminPanels.create endpoint"),
            ("adminPanels", "update", "api", "adminPanels.update endpoint"),
            ("adminPanels", "delete", "api", "adminPanels.delete endpoint"),
            ("adminPanels", "configureAuth", "api", "adminPanels.configureAuth endpoint"),
            ("entitlements", "entitlements", "page", "entitlements page"),
            ("entitlements", "view", "api", "entitlements.view endpoint"),
            ("entitlements", "update", "api", "entitlements.update endpoint"),
            ("audit", "audit", "page", "audit page"),
            ("audit", "view", "api", "audit.view endpoint"),
            ("audit", "export", "api", "audit.export endpoint"),
            ("platformSettings", "platformSettings", "page", "platformSettings page"),
            ("platformSettings", "view", "api", "platformSettings.view endpoint"),
            ("platformSettings", "update", "api", "platformSettings.update endpoint")`);
  }

  public async down(): Promise<void> {
    // Intentionally empty: removing catalog rows requires revoking
    // every grant that references them first.
  }
}
