-- GENERATED by `npm run handover:generate` — DO NOT EDIT BY HAND.
-- Source: mysqldump --no-data of a fully migrated database.
-- Regenerate after any migration; never patch this file.

/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `admin_panels` (
  `id` char(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` datetime(6) DEFAULT NULL,
  `deleted_marker` varchar(36) GENERATED ALWAYS AS (if((`deleted_at` is null),_utf8mb4'',`id`)) STORED NOT NULL,
  `name` varchar(100) NOT NULL,
  `panel_key` varchar(100) NOT NULL,
  `is_active` tinyint NOT NULL DEFAULT '0',
  `theme` varchar(30) NOT NULL DEFAULT 'default',
  `basic_auth_enabled` tinyint NOT NULL DEFAULT '0',
  `sso_auth_enabled` tinyint NOT NULL DEFAULT '0',
  `sso_tenant_id` varchar(64) DEFAULT NULL,
  `sso_client_id` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_admin_panels_key` (`panel_key`,`deleted_marker`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `auth_audit_events` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `actor_user_id` char(36) DEFAULT NULL,
  `event_type` varchar(64) NOT NULL,
  `outcome` enum('success','failure','denied') NOT NULL,
  `target_type` varchar(64) DEFAULT NULL,
  `target_id` varchar(64) DEFAULT NULL,
  `admin_panel_id` char(36) DEFAULT NULL,
  `ip` varchar(64) DEFAULT NULL,
  `geo_country` char(2) DEFAULT NULL,
  `geo_city` varchar(128) DEFAULT NULL,
  `geo_asn` varchar(64) DEFAULT NULL,
  `user_agent` varchar(512) DEFAULT NULL,
  `jti` char(36) DEFAULT NULL,
  `request_id` varchar(128) DEFAULT NULL,
  `metadata` json DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `idx_auth_audit_created` (`created_at`),
  KEY `idx_auth_audit_type_created` (`event_type`,`created_at`),
  KEY `idx_auth_audit_target` (`target_type`,`target_id`),
  KEY `idx_auth_audit_actor_created` (`actor_user_id`,`created_at`)
) ENGINE=InnoDB AUTO_INCREMENT=88 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `invitation_admin_panels` (
  `invitation_id` char(36) NOT NULL,
  `admin_panel_id` char(36) NOT NULL,
  PRIMARY KEY (`invitation_id`,`admin_panel_id`),
  KEY `IDX_d8ab2781990a67106f23b821d4` (`invitation_id`),
  KEY `IDX_b2472a3c100bdd1db77d242433` (`admin_panel_id`),
  CONSTRAINT `FK_b2472a3c100bdd1db77d242433c` FOREIGN KEY (`admin_panel_id`) REFERENCES `admin_panels` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_d8ab2781990a67106f23b821d4d` FOREIGN KEY (`invitation_id`) REFERENCES `invitations` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `invitation_projects` (
  `invitation_id` char(36) NOT NULL,
  `project_id` char(36) NOT NULL,
  PRIMARY KEY (`invitation_id`,`project_id`),
  KEY `IDX_b9a2b1f1835f0c256b021d6844` (`invitation_id`),
  KEY `IDX_9490b4e370e68ddaaf7520ad0b` (`project_id`),
  CONSTRAINT `FK_9490b4e370e68ddaaf7520ad0b6` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_b9a2b1f1835f0c256b021d6844e` FOREIGN KEY (`invitation_id`) REFERENCES `invitations` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `invitations` (
  `id` char(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `token_hash` char(64) NOT NULL,
  `email` varchar(255) NOT NULL,
  `status` enum('created','sent','accepted','rejected','expired') NOT NULL DEFAULT 'created',
  `expires_at` datetime(6) NOT NULL,
  `sent_at` datetime(6) DEFAULT NULL,
  `accepted_at` datetime(6) DEFAULT NULL,
  `invited_by_user_id` char(36) DEFAULT NULL,
  `rejected_reason` varchar(255) DEFAULT NULL,
  `accepted_oid` char(36) DEFAULT NULL,
  `accepted_first_name` varchar(100) DEFAULT NULL,
  `accepted_last_name` varchar(100) DEFAULT NULL,
  `accepted_language` varchar(2) DEFAULT NULL,
  `role_id` char(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_invitations_token_hash` (`token_hash`),
  KEY `idx_invitations_status_expires` (`status`,`expires_at`),
  KEY `idx_invitations_email` (`email`),
  KEY `FK_e4950c4d6aa2236f5213538e01a` (`role_id`),
  CONSTRAINT `FK_e4950c4d6aa2236f5213538e01a` FOREIGN KEY (`role_id`) REFERENCES `user_roles` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `login_lockouts` (
  `user_id` char(36) NOT NULL,
  `failure_count` int unsigned NOT NULL DEFAULT '0',
  `last_failure_at` datetime(6) DEFAULT NULL,
  `locked_until` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`user_id`),
  KEY `idx_login_lockouts_locked_until` (`locked_until`),
  CONSTRAINT `FK_1f8f5b3a00155858eaa73edca97` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `migrations` (
  `id` int NOT NULL AUTO_INCREMENT,
  `timestamp` bigint NOT NULL,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `permission_catalog` (
  `section` varchar(64) NOT NULL,
  `permission_key` varchar(64) NOT NULL,
  `kind` enum('page','api') NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`section`,`permission_key`,`kind`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `platform_settings` (
  `id` tinyint unsigned NOT NULL DEFAULT '1',
  `sso_tenant_id` varchar(64) DEFAULT NULL,
  `sso_client_id` varchar(64) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  CONSTRAINT `chk_platform_settings_singleton` CHECK ((`id` = 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `project_blockers` (
  `id` char(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `project_id` char(36) NOT NULL,
  `player_blockers` json DEFAULT NULL,
  `reason` json DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `REL_8ab0dd779ee4ce6aa00f639fac` (`project_id`),
  CONSTRAINT `FK_8ab0dd779ee4ce6aa00f639fac1` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `project_entitlements` (
  `project_id` char(36) NOT NULL,
  `section` varchar(64) NOT NULL,
  `permission_key` varchar(64) NOT NULL,
  `kind` enum('page','api') NOT NULL,
  PRIMARY KEY (`project_id`,`section`,`permission_key`,`kind`),
  KEY `idx_project_entitlements_catalog` (`section`,`permission_key`,`kind`),
  CONSTRAINT `FK_419934e558c3da9c62522bc0812` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_f8ca791e78128e3a4592216e4d8` FOREIGN KEY (`section`, `permission_key`, `kind`) REFERENCES `permission_catalog` (`section`, `permission_key`, `kind`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `project_limits` (
  `id` char(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `project_id` char(36) NOT NULL,
  `project_key` varchar(255) NOT NULL,
  `currency` varchar(10) NOT NULL,
  `daily_withdraw_limit` decimal(18,2) NOT NULL DEFAULT '0.00',
  `sport_winning_limit` decimal(18,2) NOT NULL DEFAULT '0.00',
  `casino_winning_limit` decimal(18,2) NOT NULL DEFAULT '0.00',
  `games_winning_limit` decimal(18,2) NOT NULL DEFAULT '0.00',
  `sport_ggr_limit` decimal(18,2) NOT NULL DEFAULT '0.00',
  `casino_ggr_limit` decimal(18,2) NOT NULL DEFAULT '0.00',
  `games_ggr_limit` decimal(18,2) NOT NULL DEFAULT '0.00',
  `used_unused_percentage` decimal(18,2) NOT NULL DEFAULT '50.00',
  `rollback_limit_percentage` decimal(18,2) DEFAULT '0.00',
  `mi_limit` decimal(10,0) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_project_limits_project_currency` (`project_id`,`currency`),
  CONSTRAINT `FK_51d085f2ecc5a9e05944f7e2eb1` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `project_operator_op_types` (
  `id` char(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `operator_id` char(36) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `type` enum('IN','OUT') NOT NULL DEFAULT 'IN',
  `auto_push_enabled` tinyint NOT NULL DEFAULT '0',
  `auto_approve_enabled` tinyint NOT NULL DEFAULT '0',
  `manual_insert_status` tinyint NOT NULL DEFAULT '0',
  `approved_trx_reports` tinyint NOT NULL DEFAULT '0',
  `payment_trx_id_required_level` enum('NONE','OPTIONAL','REQUIRED') NOT NULL DEFAULT 'OPTIONAL',
  `remote_trx_id_required_level` enum('NONE','OPTIONAL','REQUIRED') NOT NULL DEFAULT 'OPTIONAL',
  `reason_required_level` enum('NONE','OPTIONAL','REQUIRED') NOT NULL DEFAULT 'OPTIONAL',
  `currencies` json DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_project_operator_op_types_operator` (`operator_id`),
  CONSTRAINT `FK_c40b25f4cdf7aac63e6cd71fda9` FOREIGN KEY (`operator_id`) REFERENCES `project_operators` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `project_operators` (
  `id` char(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `project_id` char(36) NOT NULL,
  `op_name` varchar(255) NOT NULL,
  `auto_push_enabled` tinyint NOT NULL DEFAULT '0',
  `auto_approve_enabled` tinyint NOT NULL DEFAULT '0',
  `auto_push_exist` tinyint NOT NULL DEFAULT '0',
  `auto_approve_exist` tinyint NOT NULL DEFAULT '0',
  `auto_approve_status_updated_at` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_project_operators_project_name` (`project_id`,`op_name`),
  CONSTRAINT `FK_bfd37282d746279d5bfa4a9f17c` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `projects` (
  `id` char(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` datetime(6) DEFAULT NULL,
  `deleted_marker` varchar(36) GENERATED ALWAYS AS (if((`deleted_at` is null),_utf8mb4'',`id`)) STORED NOT NULL,
  `name` varchar(100) NOT NULL,
  `project` varchar(255) NOT NULL,
  `project_db` varchar(255) NOT NULL,
  `project_tz` varchar(255) DEFAULT NULL,
  `logo_url` text,
  `is_active` tinyint NOT NULL DEFAULT '0',
  `theme` varchar(30) NOT NULL DEFAULT 'default',
  `is_using_bulk_tr` tinyint NOT NULL DEFAULT '0',
  `is_multi_currency` tinyint NOT NULL DEFAULT '0',
  `app_types` json DEFAULT NULL,
  `additional_trx_types` json DEFAULT NULL,
  `project_phone_country_code` varchar(10) DEFAULT NULL,
  `restore_bet_history_days_count` int unsigned NOT NULL DEFAULT '30',
  `manual_check_exist` tinyint NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_projects_project_db` (`project_db`,`deleted_marker`),
  UNIQUE KEY `uq_projects_project` (`project`,`deleted_marker`),
  KEY `idx_projects_is_active` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `refresh_tokens` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` char(36) NOT NULL,
  `token_hash` char(64) NOT NULL,
  `family_id` char(36) NOT NULL,
  `issued_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `expires_at` datetime(6) NOT NULL,
  `revoked_at` datetime(6) DEFAULT NULL,
  `revoked_reason` varchar(64) DEFAULT NULL,
  `ip` varchar(64) DEFAULT NULL,
  `user_agent` varchar(512) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_refresh_tokens_hash` (`token_hash`),
  KEY `idx_refresh_tokens_family` (`family_id`),
  KEY `idx_refresh_tokens_user_expires` (`user_id`,`expires_at`),
  CONSTRAINT `FK_3ddc983c5f7bcf132fd8732c3f4` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=35 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `role_permissions` (
  `role_id` char(36) NOT NULL,
  `section` varchar(64) NOT NULL,
  `permission_key` varchar(64) NOT NULL,
  `kind` enum('page','api') NOT NULL,
  PRIMARY KEY (`role_id`,`section`,`permission_key`,`kind`),
  KEY `idx_role_permissions_catalog` (`section`,`permission_key`,`kind`),
  CONSTRAINT `FK_178199805b901ccd220ab7740ec` FOREIGN KEY (`role_id`) REFERENCES `user_roles` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_888d20ef4febc39d60384bd396d` FOREIGN KEY (`section`, `permission_key`, `kind`) REFERENCES `permission_catalog` (`section`, `permission_key`, `kind`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `two_factor_state` (
  `user_id` char(36) NOT NULL,
  `is_enabled` tinyint NOT NULL DEFAULT '0',
  `secret_encrypted` varchar(255) DEFAULT NULL,
  `pending_secret_encrypted` varchar(255) DEFAULT NULL,
  `pending_expires_at` datetime(6) DEFAULT NULL,
  `key_version` smallint unsigned NOT NULL DEFAULT '1',
  `confirmed_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`user_id`),
  CONSTRAINT `FK_38f45652401b2e99719e2c84945` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `typeorm_metadata` (
  `type` varchar(255) NOT NULL,
  `database` varchar(255) DEFAULT NULL,
  `schema` varchar(255) DEFAULT NULL,
  `table` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `value` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `user_admin_panels` (
  `user_id` char(36) NOT NULL,
  `admin_panel_id` char(36) NOT NULL,
  PRIMARY KEY (`user_id`,`admin_panel_id`),
  KEY `IDX_fdad28cecab828c37a9e8d660d` (`user_id`),
  KEY `IDX_da267d1cd8cb43d615a7e47936` (`admin_panel_id`),
  CONSTRAINT `FK_da267d1cd8cb43d615a7e47936b` FOREIGN KEY (`admin_panel_id`) REFERENCES `admin_panels` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_fdad28cecab828c37a9e8d660da` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `user_project_permissions` (
  `user_id` char(36) NOT NULL,
  `project_id` char(36) NOT NULL,
  `section` varchar(64) NOT NULL,
  `permission_key` varchar(64) NOT NULL,
  `kind` enum('page','api') NOT NULL,
  `effect` enum('deny','grant') NOT NULL DEFAULT 'deny',
  PRIMARY KEY (`user_id`,`project_id`,`section`,`permission_key`,`kind`),
  KEY `idx_user_project_permissions_project` (`project_id`),
  KEY `idx_user_project_permissions_catalog` (`section`,`permission_key`,`kind`),
  CONSTRAINT `FK_1b61a0c323bd6a18260f5bedb18` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_2532c7792c2d9c6753781635839` FOREIGN KEY (`section`, `permission_key`, `kind`) REFERENCES `permission_catalog` (`section`, `permission_key`, `kind`) ON DELETE RESTRICT,
  CONSTRAINT `FK_9b1ea4bb460a9bd4b3dfd1f7dd5` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `user_projects` (
  `user_id` char(36) NOT NULL,
  `project_id` char(36) NOT NULL,
  PRIMARY KEY (`user_id`,`project_id`),
  KEY `IDX_86ef6061f6f13aa9252b12cbe8` (`user_id`),
  KEY `IDX_4c6aaf014ba0d66a74bb552272` (`project_id`),
  CONSTRAINT `FK_4c6aaf014ba0d66a74bb5522726` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `FK_86ef6061f6f13aa9252b12cbe87` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `user_roles` (
  `id` char(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` datetime(6) DEFAULT NULL,
  `deleted_marker` varchar(36) GENERATED ALWAYS AS (if((`deleted_at` is null),_utf8mb4'',`id`)) STORED NOT NULL,
  `name` varchar(100) NOT NULL,
  `is_public` tinyint NOT NULL DEFAULT '0',
  `description` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_user_roles_name` (`name`,`deleted_marker`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!50503 SET character_set_client = utf8mb4 */;
CREATE TABLE `users` (
  `id` char(36) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `deleted_at` datetime(6) DEFAULT NULL,
  `deleted_marker` varchar(36) GENERATED ALWAYS AS (if((`deleted_at` is null),_utf8mb4'',`id`)) STORED NOT NULL,
  `oid` char(36) DEFAULT NULL,
  `username` varchar(100) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) DEFAULT NULL,
  `first_name` varchar(100) DEFAULT NULL,
  `last_name` varchar(100) DEFAULT NULL,
  `phone` varchar(100) DEFAULT NULL,
  `is_active` tinyint NOT NULL DEFAULT '0',
  `is_sp_reset` tinyint NOT NULL DEFAULT '0',
  `sp_updated_at` datetime(6) DEFAULT NULL,
  `language` varchar(2) NOT NULL DEFAULT 'en',
  `timezone` varchar(50) DEFAULT NULL,
  `token_epoch` int unsigned NOT NULL DEFAULT '0',
  `role_id` char(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_users_username` (`username`,`deleted_marker`),
  UNIQUE KEY `uq_users_email` (`email`,`deleted_marker`),
  UNIQUE KEY `uq_users_oid` (`oid`,`deleted_marker`),
  KEY `idx_users_is_active` (`is_active`),
  KEY `FK_a2cecd1a3531c0b041e29ba46e1` (`role_id`),
  CONSTRAINT `FK_a2cecd1a3531c0b041e29ba46e1` FOREIGN KEY (`role_id`) REFERENCES `user_roles` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
/*!40101 SET character_set_client = @saved_cs_client */;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

